global:
  namespace: monitoring

# https://semaphoreci.com/blog/prometheus-grafana-kubernetes-helm
grafana:
  persistence:
    enabled: true
    storageClassName: pvc
    # TODO: leverage longhorn backups
    # existingClaim: grafana-pvc

  # dataSources:
  #   - name: prometheus
  #     url: http://prometheus-server

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
