---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: paperless-ngx-env-vaultsecret-ref
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: in-cluster
  # takes all keys in this "dir" and puts them into an opaque secret
  path: paperless-ngx/env
  destination:
    name: paperless-ngx-env-secrets
    create: true
  refreshAfter: 30s
  # VERY IMPORTANT - VSO operator needs to know _which_ NS our auth lives in
  vaultAuthRef: {{ .Release.Namespace -}}/paperless-ngx-vso-connection-auth
