apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: paperless-ngx-env-vaultsecret-ref
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: paperless-ngx
  path: env/PAPERLESS_SOCIALACCOUNT_PROVIDERS
  destination:
    name: paperless-ngx-env-secrets
    create: true
  refreshAfter: 30s
  # vaultAuthRef: vault-auth-on-prem-vault-auth
