# NOTE: we use a submodule here because the dir itself does not _actually_ support
# kustomize (e.g.: read the comments in kustomization.yaml in this dir)
resources:
- ./ingress-nginx/deploy/static/provider/baremetal/deploy.yaml

patches:
- target:
    kind: Service
    name: ingress-nginx-controller
  path: ./ingress-patch.yaml
