---
apiVersion: 1.0.0
name: stirling-pdf
version: 0.0.1
description: simple stirling-pdf installation
type: application

dependencies:
  - name: stirling-pdf
    version: ~3
    repository: https://stirling-tools.github.io/Stirling-PDF-chart

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress
