traefik-ingress:
  dnsNames:
    - dns: stirling-pdf.rannet.duckdns.org
      services:
        - kind: Service
          name: stirling-pdf
          port: http

cnpg:
  image: ghcr.io/tensorchord/cloudnative-vectorchord:17-0.4.3
  instances: 2

stirling-pdf:
  resources:
    requests:
      cpu: 1
      memory: 4G
    limits:
      cpu: 2
      memory: 8G

  # TODO: figure out later
  # securityContext:
  #   enabled: true
  #   fsGroup: 1000
  #   # Optionally, specify supplementalGroups and/or
  #   # runAsNonRoot for security purposes
  #   runAsNonRoot: true
  #   supplementalGroups: [1000]

  envs:
    # https://docs.stirlingpdf.com/Installation/Docker%20Install#simple-deployment-recommended
    - name: MODE
      value: BOTH
    - name: SYSTEM_DATASOURCE_ENABLECUSTOMDATABASE
      value: "true"
    - name: SYSTEM_DATASOURCE_CUSTOMDATABACKENDURL
      value: "jdbc:postgresql://stirling-pdf-rw:5432/stirling_pdf"
    - name: SYSTEM_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          name: stirling-pdf-superuser
          key: username
    - name: SYSTEM_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: stirling-pdf-superuser
          key: password

  # persistence:
  #   enabled: true
  #   size: 8Gi
  #   storageClass: longhorn
  #   # TODO
  #   # volumeName: <>
