namespace: homepage


helmCharts:
- name: homepage
  includeCRDs: false
  releaseName: homepage
  namespace: homepage
  repo: https://jameswynn.github.io/helm-charts
  valuesInline:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: latest
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "home.k8s:30443,home.k8s:30080,rannet.duckdns.org"

resources:
- ./ingress.yaml
- ./sa.yaml
- ./cluster-role-and-binding.yaml

patches:
- path: ./config-map.yaml
  target:
    kind: ConfigMap
    name: homepage

- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        configmap.reloader.stakater.com/reload: "homepage"
  target:
      kind: Deployment
      name: homepage

