namespace: homepage


helmCharts:
- name: homepage
  includeCRDs: false
  releaseName: homepage
  namespace: homepage
  repo: https://jameswynn.github.io/helm-charts
  valuesInline:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: latest

resources:
- ./ingress.yaml
- ./sa.yaml
- ./cluster-role-and-binding.yaml

patches:
- path: ./config-map.yaml
  target:
    kind: ConfigMap
    name: homepage

- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        configmap.reloader.stakater.com/reload: "homepage"
  target:
      kind: Deployment
      name: homepage

