version: 2
updates:
  - package-ecosystem: "helm" # See documentation for possible values
    directories:
      - "k8s/argocd-deploy/**/**/*"
      - "k8s/helm/**/**/*"
    schedule:
      interval: "daily"
