traefik-ingress:
  dnsNames:
    - dns: komga.rannet.duckdns.org
      services:
        - kind: Service
          name: komga
          port: http

vault-auth:
  vaultConnectionName: vault-secrets-operator/default
  authMethods:
    - name: on-prem
      vaultAuthName: komga-vso-connection-auth
      method: kubernetes
      mount: in-cluster
      config:
        role: komga
        serviceAccount: komga
        audiences:
          - vault

komga:
  controllers:
    main:

      type: deployment
      strategy: RollingUpdate
      rollingUpdate:
        unavailable: 1
      containers:
        main:
          image:
            pullPolicy: Always
            repository: ghcr.io/gotson/komga
            tag: 1.26.3

          env:
            TZ: America/New_York
            KOMGA_DATABASE_CHECKLOCALFILESYSTEM: "FALSE"
            KOMGA_TASKSDB_CHECKLOCALFILESYSTEM: "FALSE"

  persistence:

    data:
      type: persistentVolumeClaim
      accessMode: ReadWriteMany
      storageClass: smb
      size: 8Gi
      retain: true
      advancedMounts:
        main:   # main controller
          main: # main container
            - path: /data

    config:
      type: persistentVolumeClaim
      accessMode: ReadWriteMany
      storageClass: smb
      size: 8Gi
      retain: true
      advancedMounts:
        main:   # main controller
          main: # main container
            - path: /config

  service:
    komga:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 25600
