{{- range .Values.authMethods }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  # namespace: {{ $.Release.Namespace }}
  {{- if .vaultAuthName }}
  name: {{ .vaultAuthName }}
  {{- else }}
  name: {{ $.Values.releaseName | default "vault" }}-{{ .name }}-auth
  {{- end }}
spec:
  {{- if $.Values.vaultConnectionName }}
  vaultConnectionRef: {{ $.Values.vaultConnectionName }}
  {{- else }}
  vaultConnectionRef: default
  {{- end }}
  method: {{ .method }}
  mount: {{ .mount }}
  {{ .method }}:
{{ toYaml .config | indent 4 }}
{{- end }}
