apiVersion: 1.0.0
name: npm
version: 0.0.1
description: simple NPM installation
type: application

dependencies:
  - name: nginx-proxy-manager
    repository: https://chr0n1x.github.io/nginx-proxy-manager-on-kubernetes
    version: ">= 0.0.3"
