{{- if .Values.backupTarget.cifs.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: cifs-backup-target-creds
  namespace: {{ .Values.longhorn.namespaceOverride | default .Release.Namespace }}
type: Opaque
data:
  CIFS_USERNAME: {{ .Values.backupTarget.cifs.username | b64enc }}
  CIFS_PASSWORD: {{ .Values.backupTarget.cifs.password | b64enc }}
{{- end -}}
