apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repo.url }}
    path: k8s/argocd-deploy/grafana
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../values.yaml
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      # secret flaps, which then causes RS to flap...?
      prune: false
      selfHeal: true
      allowEmpty: true
