apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repo.url }}
    path: k8s/argocd-deploy/ollama
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    # prevent autosync for now
    # waiting on something like this:
    #   https://github.com/otwld/ollama-helm/pull/89
    automated: {}
      # selfHeal: true
      # prune: true
    syncOptions:
      - CreateNamespace=true
