apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pinchflat
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repo.url }}
    path: k8s/argocd-deploy/pinchflat
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../values.yaml
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pinchflat
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
