# helm repo add descheduler https://kubernetes-sigs.github.io/descheduler/
# helm install descheduler --namespace kube-system descheduler/descheduler
#
# for more info on default installation:
#   https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/README.md
#

---
apiVersion: descheduler/v1alpha2
kind: DeschedulerPolicy
metadata:
  namespace: kube-system
  name: descheduler-low-node-pol
profiles:
  - name: LowNodeDeschedulerProf
    pluginConfig:
    - name: "LowNodeUtilization"
      args:
        thresholds:
          "cpu": 20
          "memory": 20
          "pods": 20
        targetThresholds:
          "cpu": 50
          "memory": 50
          "pods": 50
    plugins:
      balance:
        enabled:
          - "LowNodeUtilization"
