---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  namespace: {{ .Values.global.namespaceOverride }}
spec:
  imageName: {{ .Values.cnpg.image }}
  instances: 2

  enableSuperuserAccess: true

  managed:
    roles:
      - name: {{ .Values.cnpg.roleName }}
        superuser: true
        login: true
        passwordSecret:
          name: authentik-postgres-user

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres-user
  storage:
    size: 8Gi
    storageClass: longhorn
