# completely based on the VSO setup here:
#
# you CAN configure everything via the UI; for the k8s auth method, you can get
# a URL for your API by exec'ing into a vault pod and running:
#
#   echo https://${KUBERNETES_PORT_443_TCP_ADDR}:443
releaseName: "vault-auth"
vaultConnectionName: vso-namespace/vaultconnection-name

authMethods: []

  # example
  # - name: default-cluster-k8s-auth
  #   method: kubernetes
  #   mount: kubernetes
  #   config:
  #     role: default-role
  #     serviceAccount: default
  #     # optional configuration injected directly into config
  #     # ns where the auth backend is mounted (requires Vault Enterprise)
  #     namespace: ""
  #     # Params to use when authenticating to Vault
  #     params: []
  #     # HTTP headers to be included in all Vault authentication requests.
  #     headers: []
