{{- if .Values.argocdWatch.enabled }}
{{- with .Values.argocdWatch.vault }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-watch
  namespace: {{ $.Release.Namespace }}
spec:
  type: kv-v2
  mount: {{ .mount }}
  path: {{ .path }}
  destination:
    name: argocd-watch
    create: true
    overwrite: true
  refreshAfter: 30s
  vaultAuthRef: {{ $.Release.Namespace }}/argocd-vso-connection-auth
{{- end }}
{{- end }}
