---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.repo.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: {{ .Values.repo.url }}
  username: {{ .Values.repo.username }}
  password: {{ .Values.repo.token }}
