apiVersion: 1.0.0
name: trivy
version: 1.0.0
description: trivy wrapper chart
type: application

dependencies:
  - name: trivy-operator
    version: ~0.28
    repository: https://aquasecurity.github.io/helm-charts/
