trivy-operator:
  image:
    registry: mirror.gcr.io
    repository: aquasec/trivy-operator

  trivy:
    image:
      registry: mirror.gcr.io
      repository: aquasec/trivy
      tag: "0.74.0"
    storageClassEnabled: true
    storageClassName: longhorn
    storageSize: "4Gi"

  operator:
    builtInTrivyServer: true

vault-auth:
  vaultConnectionName: vault-secrets-operator/default
  authMethods:
    - name: trivy-reporter
      vaultAuthName: trivy-reporter-vault-auth
      method: kubernetes
      mount: in-cluster
      config:
        role: trivy
        serviceAccount: trivy-trivy-operator
        audiences:
          - vault
