trivy-operator:
  image:
    registry: mirror.gcr.io
    repository: aquasec/trivy-operator

  trivy:
    image:
      registry: mirror.gcr.io
      repository: aquasec/trivy
      tag: "0.74.0"
    storageClassEnabled: true
    storageClassName: longhorn
    storageSize: "4Gi"

  operator:
    builtInTrivyServer: true
