trivy:
  operator:
    builtInTrivyServer: false
    builtInServerRegistryInsecure: false

  trivy:
    mode: Standalone

  trivyOperator:
    scanJobPodTemplateContainerSecurityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
          - ALL
      privileged: true
      readOnlyRootFilesystem: true
