# https://github.com/immich-app/immich-charts/issues/149
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  namespace: immich
spec:
  imageName: {{ .Values.cnpg.image }}
  instances: 1

  postgresql:
    shared_preload_libraries:
      - "vchord.so"
      # - "vectors.so"

  # The "postgres" superuser is needed only for import and it can be
  # deactivated after migration.
  enableSuperuserAccess: true
  # superuserSecret: immich-superuser

  managed:
    roles:
      - name: immich
        superuser: true
        login: true
        passwordSecret:
          name: immich-postgres-user

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-user
      postInitSQL:
          # only use with vchord.so above
          - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;
          - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

          # - CREATE EXTENSION IF NOT EXISTS "vectors";
          # - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
          # - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
  storage:
    size: 8Gi
    storageClass: longhorn
