---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-store-pvc
  namespace: {{ .Release.Namespace }}
  finalizers:
    - kubernetes.io/pvc-protection
  # uid: 9108f24f-5220-488c-a91a-9bd88f584ed9
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi
  storageClassName: smb
  volumeMode: Filesystem
