vault-secrets-operator:
  defaultVaultConnection:
     enabled: true
     address: "http://vault.vault.svc.cluster.local:8200"
     skipTLSVerify: true

  controller:
    manager:
      clientCache:
        persistenceModel: direct-encrypted
        storageEncryption:
          enabled: true
          mount: in-cluster
          keyName: vso-client-cache
          transitMount: in-cluster-transit
          kubernetes:
            role: auth-role-operator
            serviceAccount: vault-secrets-operator-controller-manager
            tokenAudiences: ["vault"]
