apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: duckdns-updater-credentials
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: in-cluster
  path: cert-manager/duckdns
  destination:
    name: duckdns-updater-credentials
    create: true
    overwrite: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Release.Namespace -}}/cert-manager-vso-connection-auth
