# talosctl -n <node ip> patch mc --patch @talos/config-nvidia.patch.yaml
machine:
  install:
    # 535 OSS
    # image: factory.talos.dev/installer/c01e496fb4958bfa0534b1fc9d3e393fdd23e18486302042144863fed6b02950:v1.9.4
    # 550x proprietary
    image: factory.talos.dev/installer/c35d5bd14fd96abc839f9f44f5effd00c48f654edb8a42648f4b2eb6051d1dd6:v1.9.4
  kernel:
    modules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
  sysctls:
    net.core.bpf_jit_harden: 1
