---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-docker-registry-pvc
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteMany

  {{- if (.Values.persistence).class }}
  storageClassName: {{ .Values.persistence.class }}
  {{- end }}

  resources:
    requests:
      storage: {{ (.Values.persistence).size | default "128Gi" }}

  {{- if (.Values.persistence).volumeName }}
  volumeName: {{ .Values.persistence.volumeName }}
  {{- end -}}
