apiVersion: 1.0.0
name: docker-registry
version: 1.0.0
description: docker-registry wrapper chart
type: application

# manifests copied/based on:
#   https://rpi4cluster.com/k3s-docker-registry/
#
# registry container docs:
#   https://distribution.github.io/distribution/about/
#
# to use, you must edit docker config to include this top-level attribute
#
# {
#    "insecure-registries" : [ "hostname.cloudapp.net:5000" ]
# }
#
# have the hostname point to the ingress

dependencies:
  - name: docker-registry
    version: ~1
    repository: https://helm.joxit.dev
