
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: owui-db
  namespace: ollama
spec:
  imageName: {{ .Values.cnpg.image }}
  instances: {{ .Values.cnpg.instances }}

  enableSuperuserAccess: true

  managed:
    roles:
      - name: owui
        superuser: true
        login: true
        # this secret does not exist on init, so I think cnpg uses some random
        # secret it generates itself
        passwordSecret:
          name: owui-postgres-user

  bootstrap:
    initdb:
      database: owui
      owner: owui
      secret:
        # this secret is created by cnpg; super important to use THIS one for
        # bootstrapping or replicas flap
        name: owui-db-superuser
  storage:
    size: 32Gi
    storageClass: longhorn

