{{- with index .Values "open-webui" }}
{{- with .ollama.persistentVolume }}
{{- if .enabled }}
{{- if .existingClaim }}
{{- if .volumeName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: {{ .existingClaim }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    argocd.argoproj.io/instance: {{ .Chart.Name }}
  name: {{ .existingClaim }}
  # uid: 9108f24f-5220-488c-a91a-9bd88f584ed9
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClass }}
  volumeMode: Filesystem
  volumeName: {{ .volumeName }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
