# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   finalizers:
#     - kubernetes.io/pvc-protection
#   labels:
#     app.kubernetes.io/component: open-webui-pipelines
#     app.kubernetes.io/instance: ollama
#     argocd.argoproj.io/instance: ollama
#   name: open-webui-pipelines
#   # uid: 9108f24f-5220-488c-a91a-9bd88f584ed9
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: smb
#   volumeMode: Filesystem
#   # TODO: inject via values
#   volumeName: pvc-9108f24f-5220-488c-a91a-9bd88f584ed9
