{{ $chartName := .Chart.Name }}
{{- with index .Values "open-webui" }}
{{- if .pipelines.persistence.enabled }}
{{- if .pipelines.persistence.existingClaim }}
{{- if .pipelines.persistence.volumeName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: {{ .pipelines.persistence.existingClaim }}
    app.kubernetes.io/instance: {{ $chartName }}
    argocd.argoproj.io/instance: {{ $chartName }}
  name: {{ .pipelines.persistence.existingClaim }}
  # uid: 9108f24f-5220-488c-a91a-9bd88f584ed9
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .pipelines.persistence.size }}
  storageClassName: {{ .pipelines.persistence.storageClass }}
  volumeMode: Filesystem
  volumeName: {{ .pipelines.persistence.volumeName }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
