{{ $chartName := .Chart.Name }}

{{- with index .Values "open-webui" }}
{{- with .ollama.persistentVolume }}
{{- if .enabled }}
{{- if .existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: {{ .existingClaim }}
    app.kubernetes.io/instance: {{ $chartName }}
    argocd.argoproj.io/instance: {{ $chartName }}
  name: {{ .existingClaim }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClass }}
  volumeMode: Filesystem
  {{- if .volumeName }}
  volumeName: {{ .volumeName }}
  {{- end }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}
