apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-reporter-state
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
