apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: trivy-reporter
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-reporter-vuln-reports
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregate-vulnerability-reports-view
subjects:
  - kind: ServiceAccount
    name: trivy-reporter
    namespace: {{ .Release.Namespace }}
