apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: trivy-telegram
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: in-cluster
  path: trivy/telegram
  destination:
    name: trivy-telegram
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Release.Namespace }}/trivy-reporter-vault-auth
