# manifests copied/based on:
#   https://rpi4cluster.com/k3s-docker-registry/
#
# registry container docs:
#   https://distribution.github.io/distribution/about/
#
# to use, you must edit docker config to include this top-level attribute
#
# {
#    "insecure-registries" : [ "hostname.cloudapp.net:5000" ]
# }
#
# have the hostname point to the ingress

namespace: docker-registry

helmCharts:
- name: docker-registry-ui
  includeCRDs: false
  releaseName: docker-registry
  namespace: docker-registry
  repo: https://helm.joxit.dev
  version: ~1
  valuesInline:
    registry:
      enabled: true
      dataVolume:
        persistentVolumeClaim:
          claimName: longhorn-docker-registry-pvc
      ingress:
        enabled: true
        host: docker.home.k8s
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    ui:
      ingress:
          enabled: true
          # automatically has a prefix of /v2
          host: docker.home.k8s
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
            nginx.ingress.kubernetes.io/ssl-passthrough: "false"
            nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.home.k8s:30443/oauth2/auth
            # don't feel too good about this; ideally should be $server_port, but
            # using a NodePort instead of an actual LB doesn't seem to allow this (TBD)
            nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.home.k8s:30443/oauth2/start?rd=$scheme://$host:30443$request_uri"
            nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email,X-Forwarded-Groups
resources:
- ./pvc.yaml
