# helm install homarr oci://ghcr.io/oben01/charts/homarr --namespace homarr --create-namespace --values=homarr.yaml

env:
  TZ: America/New York
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: home.k8s
      paths:
        - path: /
          pathType: Prefix
