---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwix-serve
  namespace: {{ .Release.Namespace }}
  labels:
    app: kiwix-serve
    app.kubernetes.io/instance: kiwix-serve
    app.kubernetes.io/name: kiwix-serve
spec:
  selector:
    matchLabels:
      app: kiwix-serve
      app.kubernetes.io/instance: kiwix-serve
      app.kubernetes.io/name: kiwix-serve
  replicas: 1
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  kiwix-serve
      labels:
        app: kiwix-serve
        app.kubernetes.io/instance: kiwix-serve
        app.kubernetes.io/name: kiwix-serve
    spec:
      containers:
      - name: kiwix-serve
        image: {{ .Values.deployment.image | default "ghcr.io/kiwix/kiwix-serve:3.7.0" }}
        imagePullPolicy: IfNotPresent
        args:
          {{- if .Values.deployment.otherArgs }}
            {{- with .Values.deployment.otherArgs }}
            {{- toYaml . | nindent 8 }}
            {{- end }}
          {{- end }}

          {{- if .Values.deployment.zimPaths }}
            {{- with .Values.deployment.zimPaths }}
            {{- toYaml . | nindent 8 }}
            {{- end }}
          {{- else }}
          - '/data/*.zim'
          {{- end }}

        resources:
          requests:
            cpu: {{ .Values.deployment.resources.cpu.request | default "100m" }}
            memory: {{ .Values.deployment.resources.mem.request | default "1Gi" }}
          limits:
            cpu: {{ .Values.deployment.resources.cpu.limit | default "500m" }}
            memory: {{ .Values.deployment.resources.mem.limit | default "2Gi" }}

        {{- if .Values.deployment.livenessProbe }}
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds | default 180 }}
          timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds | default 180 }}
          successThreshold: {{ .Values.deployment.livenessProbe.successThreshold | default 1 }}
          failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold | default 16 }}
          periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds | default 60 }}
        {{- end }}

        {{- if .Values.deployment.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds | default 180 }}
          timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds | default 180 }}
          successThreshold: {{ .Values.deployment.readinessProbe.successThreshold | default 1 }}
          failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold | default 16 }}
          periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds | default 60 }}
        {{- end }}

        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kiwix-pvc
      restartPolicy: Always
