---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiwix-ingress
  namespace: kiwix
  labels:
    app.kubernetes.io/name: kiwix
  annotations:
    cert-manager.io/cluster-issuer: duckdns-letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wiki.rannet.duckdns.org
      secretName: kiwix-cert
  rules:
    - host: wiki.rannet.duckdns.org
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: kiwix-svc
                port:
                  number: 8080
