---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: kiwix-serve
    app.kubernetes.io/instance: kiwix-serve
  name: kiwix-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "256Gi" }}
  storageClassName: {{ .Values.persistence.storageClassName | default "smb" }}
  volumeMode: Filesystem
  {{- if .Values.persistence.volumeName }}
  volumeName: {{ .Values.persistence.volumeName }}
  {{- end -}}
